### PR TITLE
Fix host field

### LINKED ISSUE #14: Enhancement: Send hostname in proper field
Looks like hostname is currently sent in message field. Can we send it to host field in order to use in kibana properly? Of course i can use mutate to chance but to do that for every metric entry would slow things down.

Example

    @timestamp	 	May 17th 2015, 22:00:23.229
    @version	 	1
    _id	 	AU1lZO9CdC6xzUBdJPYq
    _index	 	logstash-2015.05.18
    _source	 	{"@version":"1","@timestamp":"2015-05-18T05:00:23.229Z","message":"lsi001.scl.five9.com","events.count":190,"events.rate_1m":0.0283068306927784,"events.rate_5m":0.07300647539581288,"events.rate_15m":0.09622461742923635,"tags":["redis_metric"]}
    _type	 	logs
    #events.count	 	190
    #events.rate_15m	0.096
    #events.rate_1m	 	0.028
    #events.rate_5m	 	0.073
    message	 	lsi001.scl.five9.com
    tags	 	redis_metric

### LINKED ISSUE #18: Possible improvement by not using Socket.gethostname
In certain circumstances, "event["message"] = Socket.gethostname" may cost huge delay and render the plugin unusable. I think it might caused by hostname resolving or reverse-resolving. In my logstash use case, I changed it into 

event["message"] = event["host"] || @hostname || Socket.gethostname

@hostname is an arg I added myself.

### PR DESCRIPTION
**Pull request by gquintana**
Should fix  #18

### CODE REVIEW

File: lib/logstash/filters/metrics.rb [hunk 1]
```diff
@@ -193,7 +195,7 @@ def flush(options = {})
     return unless should_flush?
 
     event = LogStash::Event.new
-    event.set("message", Socket.gethostname)
+    event.set("host", @host)
```
Comment (jsvd) [inline lib/logstash/filters/metrics.rb]: can we keep the key in the event to `message` to avoid bumping the major version?

Comment (gquintana) [inline lib/logstash/filters/metrics.rb]: I can do that if you wish. But storing the hostname in a field named message is more a bug than a feature to me.

Shall I split this PR to place the field renaming in another one?

**Comment by gquintana** [comment]
@jsvd I did requested changes
